[package]
name = "sentiment_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
vader_sentiment = "0.1.1"  # Updated to latest available version
clap = { version = "4.4", features = ["derive"] }
